version: "3.1"
services:

    memcached:
      image: memcached:alpine
      env_file: .env
      container_name: $APP_NAME-memcached

    redis:
      image: redis:alpine
      env_file: .env
      container_name: $APP_NAME-redis

    mysql:
      image: mysql:8.0
      working_dir: /application
      env_file: .env
      container_name: $APP_NAME-mysql
      volumes:
        - .:/application
      environment:
        - MYSQL_ROOT_PASSWORD=youareroot
        - MYSQL_DATABASE=$DB_DATABASE
        - MYSQL_USER=$DB_USERNAME
        - MYSQL_PASSWORD=$DB_PASSWORD
      ports:
        - "8002:3306"

    webserver:
      image: nginx:alpine
      env_file: .env
      container_name: $APP_NAME-webserver
      working_dir: /application
      volumes:
          - .:/application
          - ./phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
       - "8000:80"

    php-fpm:
      build: phpdocker/php-fpm
      env_file: .env
      container_name: $APP_NAME-php-fpm
      working_dir: /application
      volumes:
        - .:/application
        - ./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/7.4/fpm/conf.d/99-overrides.ini

